# Make sure to create a config.yaml file in the same path

api_keys: 
  OPENAI_API_KEY: "sk-pr..."  # Your OpenAI API key
  PEXELS_API_KEY: "kGH..."  # Your Pexels API key

assets: 
  YOUTUBE_URL: "https://www.youtube.com/watch?v=eeUqAE9EH6w"  # URL of the YouTube video

video_parameters: 
  VIDEO_TOPIC: "Horror story"  # The topic of the video